site_name: DERO Documentation
theme:
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - search.share
    - content.code.copy
  logo: assets/logo.png
  favicon: assets/favicon.ico
  language: en
  name: material
  palette:
    

    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deroproject
    - icon: fontawesome/brands/discord
      link: https://discord.gg/H95TJDp
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/deroproject
    - icon: fontawesome/brands/telegram
      link: https://t.me/DeroProjectGroup
  consent:
    title: Cookie consent
    description: >- 
      At DERO, we prioritize and highly value your privacy. 
      We understand the importance of protecting your personal information, and we are committed to maintaining the confidentiality and security of any data you share with us. 
      To demonstrate our commitment to your privacy, we have implemented a transparent and cookie-free approach to data collection.
    actions:
      - accept
     
    
    
plugins:
  - privacy
  - search
  - offline


copyright: >
            Copyright &copy; 2017 - 2024 DERO Project


# Page tree
nav:
  - Home: index.md
  - Getting started:
    - DERO Node: 
      - Windows Node: getting-started/dero-node.md
      - Linux Node: getting-started/linux-node.md
      - Android node: getting-started/android-node.md
      - Windows WSL Ubuntu Full Node & Fastsync: getting-started/fastsync.md
    - Wallets:
      - Command Line Interface: getting-started/cli.md
      - Engram GUI Mobile & Desktop: getting-started/engram.md
      - Android CLI: getting-started/androidcli.md
    - Mining:
      - Mining DERO: getting-started/miningdero.md
      - Android Mining: getting-started/androidmining.md
    - Buying DERO:
      - How to buy DERO: getting-started/buyingdero.md
    - Trading:
      - Exchanges: getting-started/exchanges.md
      - Deposit to an Exchange: getting-started/deposit.md
      - Withdraw from an Exchange: getting-started/withdraw.md
    - DERO Home network:
      - Create a Home Network: getting-started/homenetwork.md
    - Smart Contracts:
      - Deploy your own Smart Contract: getting-started/smartcontract.md
  - Developers:
    - developer/dvm.md
    - developer/astrobwt.md
    - developer/DHEBP.md
    - developer/graviton.md
    - developer/RPC.md
   